
# kubectl create secret generic tumbanet-secrets \
#   --from-literal=NEXT_PUBLIC_FIREBASE_API_KEY=... \
#   --from-literal=NEXT_PUBLIC_FIREBASE_PROJECT_ID=... \
#   --from-literal=FIREBASE_CLIENT_EMAIL=... \
#   --from-literal=FIREBASE_PRIVATE_KEY=... \
#   --from-literal=VAPID_PUBLIC_KEY=... \
#   --from-literal=NEXT_PUBLIC_VAPID_PUBLIC_KEY=... \
#   --from-literal=VAPID_PRIVATE_KEY=... \
#   --from-literal=VAPID_SUBJECT=...
apiVersion: v1
kind: Secret
metadata:
  name: tumbanet-secrets
  namespace: default
type: Opaque